//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q_AManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> QuestionPaperID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string TickedAnswer { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<bool> isCorrect { get; set; }
    
        public virtual QuestionPaper QuestionPaper { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
