//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace EFDBFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryId { get; set; }
        [Required]
        public Nullable<int> EmployeeId { get; set; }
        [Required]
        public Nullable<decimal> Amount { get; set; }
        [Required]
        public string SalaryType { get; set; }
        [Required]
        public Nullable<decimal> Bonus { get; set; }
        [Required]
        public Nullable<decimal> FinalSalary { get; set; }
    }
}
